### ISSUE TITLE
4º Meetup DevOps Maringá

### ISSUE THREAD

**Issue by leonardoelias** [Devops-maringa/meetups#3]
# 4º DevOps Meetup Group Maringá - Local a confirmar
## quinta-feira, 02 de maio de 2019, 18:30
------

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo : 
```
## Meu titulo

#### Nome
Enzo

#### Grau da palestra
{Marque com um X o nível da palestra}
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Abstract
Minha talk muito legal
```

**Comment by cegohub** [comment]
## Otimização de custos em ambientes AWS

#### Tiago Amaral

#### Grau da palestra
- [x] Iniciante
- [ ] Intermediário
- [ ] Avançado

#### Abstract
Dicas e ações relevantes para otimizar custos em ambientes AWS.

**Comment by flaudisio** [comment]
## Mantendo seu código de infraestrutura com o Terragrunt

#### Nome

Flaudísio Tolentino

#### Grau da palestra

- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Abstract

Não é de hoje que o Terraform se destaca como ótima ferramenta para implementação de Infraestrutura como Código. Mas, em pouco tempo, manter e evoluir o código de vários ambientes pode se tornar algo custoso e suscetível a erros. Para isso, o Terragrunt será apresentado como uma possível solução para maior confiabilidade e DRY de seu código do Terraform.
