### ISSUE TITLE
6º DevOps Meetup Group Maringá

### ISSUE THREAD

**Issue by leonardoelias** [Devops-maringa/meetups#4]
# 6º DevOps Meetup Group Maringá - Local a confirmar
## terça-feira, 20 de agosto de 2019, 18:30
------

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1:  serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

Para submeter palestras comente nessa issue seguindo o modelo: 
```
## Meu título

#### Nome
Enzo

#### Grau da palestra
{Marque com um X o nível da palestra}
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Abstract
Minha talk muito legal
```

**Comment by geovanisouza92** [comment]
## 3 ferramentas para você implantar uma aplicação na nuvem mais rápido

#### Nome
Geovani de Souza

#### Grau da palestra
- [ ] Iniciante
- [x] Intermediário
- [ ] Avançado

#### Abstract

Como implementei uma infra do zero para uma aplicação Docker escalável usando Packer, Terraform e Ansible, com um bônus: um pipeline automático para Gitlab CI + repositório de código.

**Comment by gmdutra** [comment]
## Escalando serviços no ECS com base em uma quantidade de itens no RabbitMQ.

#### Nome
Gabriel de Moura Dutra

#### Grau da palestra

- [X] Iniciante
- [ ] Intermediário
- [ ] Avançado

#### Abstract
Essa palestra tem o objetivo de mostrar como podemos escalar serviços no ECS tendo como parâmetro o tamanho de uma determinada fila do RabbitMQ.
